apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-service-dependencies-prd-alpaca-cluster-0
  namespace: argocd
spec:
  destination:
    name: gke_ajaib-prd-alpaca_asia-southeast2_ajaib-prd-alpaca-cluster-0
  project: default
  source:
    path: app/production/prd-alpaca/dependencies
    repoURL: https://github.com/ajaibid/infra-k8s-app-manifest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-alpaca-foreign-stock-data
  namespace: argocd
spec:
  destination:
    namespace: prd-alpaca-foreign-stock-data-ns
    name: gke_ajaib-prd-alpaca_asia-southeast2_prd-alpaca-cluster-0
  project: alpaca
  source:
    path: app/production/prd-alpaca/FOREIGN-STOCK-DATA
    repoURL: https://github.com/ajaibid/infra-k8s-app-manifest
    targetRevision: HEAD
  ignoreDifferences:
    - group: flagger.app
      kind: Canary
      jsonPointers:
        - /spec/analysis/maxWeight
        - /spec/skipAnalysis
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
